name: Build and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test and calculate coverage
      run: go test -v -covermode=count -coverprofile=coverage.out ./...

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.5

    - name: Coveralls
      uses: coverallsapp/github-action@v1.0.4
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
